[package]
name = "miner"
version = "0.11.0"
edition = "2024"

[dependencies]
anyhow = "=1.0.104"
parquet = { version = "=59.3.0", default-features = false, features = ["brotli", "snap", "zstd"] }
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.151"

[profile.release]
lto = "thin"
strip = true
